"""Add FK

Revision ID: 63dc14b49234
Revises: 6c898a1d906f
Create Date: 2024-11-09 21:22:24.499932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from app.core.config import settings



# revision identifiers, used by Alembic.
revision: str = '63dc14b49234'
down_revision: Union[str, None] = '6c898a1d906f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, f'{settings.DATABASE_ORDER_ITEM_ADDON_TABLE}', f'{settings.DATABASE_ORDER_ITEM_TABLE}', ['order_item_id'], ['id'])
    op.create_foreign_key(None, f'{settings.DATABASE_ORDER_ITEM_TABLE}', f'{settings.DATABASE_ORDER_TABLE}', ['order_id'], ['id'])
    op.create_foreign_key(None, f'{settings.DATABASE_ORDER_TABLE}', 'users', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, f'{settings.DATABASE_ORDER_TABLE}', type_='foreignkey')
    op.drop_constraint(None, f'{settings.DATABASE_ORDER_ITEM_TABLE}', type_='foreignkey')
    op.drop_constraint(None, f'{settings.DATABASE_ORDER_ITEM_ADDON_TABLE}', type_='foreignkey')
    # ### end Alembic commands ###
