"""Update Driver ID

Revision ID: 89954c68c8e5
Revises: 868c2adca258
Create Date: 2024-12-11 19:06:40.361251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from app.core.config import settings



# revision identifiers, used by Alembic.
revision: str = '89954c68c8e5'
down_revision: Union[str, None] = '868c2adca258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.execute("UPDATE orders SET delivery_person_id = NULL")
    # op.alter_column('orders', 'delivery_person_id',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.Uuid(),
    #            existing_nullable=True)
    op.execute(f"""
        ALTER TABLE {settings.DATABASE_ORDER_TABLE}
        ALTER COLUMN delivery_person_id
        TYPE UUID
        USING NULL;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"""
        ALTER TABLE {settings.DATABASE_ORDER_TABLE}
        ALTER COLUMN delivery_person_id
        TYPE INTEGER
        USING NULL;
    """)
    # ### end Alembic commands ###
