definitions:
  models.AuthReq:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  models.AuthResp:
    properties:
      access_token:
        type: string
    type: object
  models.JSONResp:
    properties:
      data: {}
      message:
        type: string
      status:
        type: string
    type: object
  models.JSONerrResponse:
    properties:
      error:
        type: string
    type: object
info:
  contact:
    email: harshmittal2210@gmail.com
    name: Harsh Mittal
paths:
  /:
    get:
      description: get string by ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.JSONResp'
      summary: Hello API
      tags:
      - Ping
  /drivers/login:
    post:
      consumes:
      - application/json
      description: get login token
      parameters:
      - description: Login Body
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/models.AuthReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.AuthResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.JSONerrResponse'
      summary: Login Driver
      tags:
      - Authentication
swagger: "2.0"
