"""Add Token

Revision ID: 2b0baa80354d
Revises: 037394ce66fb
Create Date: 2024-11-15 14:24:14.006215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from app.core.config import settings



# revision identifiers, used by Alembic.
revision: str = '2b0baa80354d'
down_revision: Union[str, None] = '037394ce66fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_token_blacklist',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_token_blacklist_id'), 'system_token_blacklist', ['id'], unique=False)
    op.create_index(op.f('ix_system_token_blacklist_token'), 'system_token_blacklist', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_token_blacklist_token'), table_name='system_token_blacklist')
    op.drop_index(op.f('ix_system_token_blacklist_id'), table_name='system_token_blacklist')
    op.drop_table('system_token_blacklist')
    # ### end Alembic commands ###
