"""Add Restaurant Details

Revision ID: 037394ce66fb
Revises: daf69c52c9a8
Create Date: 2024-11-15 14:16:36.586501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from app.core.config import settings



# revision identifiers, used by Alembic.
revision: str = '037394ce66fb'
down_revision: Union[str, None] = 'daf69c52c9a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(f'{settings.DATABASE_RESTAURANT_TABLE}', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    op.add_column(f'{settings.DATABASE_RESTAURANT_TABLE}', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.add_column(f'{settings.DATABASE_RESTAURANT_TABLE}', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column(f'{settings.DATABASE_RESTAURANT_TABLE}', sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column(f'{settings.DATABASE_RESTAURANT_TABLE}', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.create_index(op.f(f'ix_{settings.DATABASE_RESTAURANT_TABLE}_email'), f'{settings.DATABASE_RESTAURANT_TABLE}', ['email'], unique=True)
    op.create_index(op.f(f'ix_{settings.DATABASE_RESTAURANT_TABLE}_phone'), f'{settings.DATABASE_RESTAURANT_TABLE}', ['phone'], unique=True)
    op.create_index(op.f(f'ix_{settings.DATABASE_RESTAURANT_TABLE}_username'), f'{settings.DATABASE_RESTAURANT_TABLE}', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f(f'ix_{settings.DATABASE_RESTAURANT_TABLE}_username'), table_name=f'{settings.DATABASE_RESTAURANT_TABLE}')
    op.drop_index(op.f(f'ix_{settings.DATABASE_RESTAURANT_TABLE}_phone'), table_name=f'{settings.DATABASE_RESTAURANT_TABLE}')
    op.drop_index(op.f(f'ix_{settings.DATABASE_RESTAURANT_TABLE}_email'), table_name=f'{settings.DATABASE_RESTAURANT_TABLE}')
    op.drop_column(f'{settings.DATABASE_RESTAURANT_TABLE}', 'is_superuser')
    op.drop_column(f'{settings.DATABASE_RESTAURANT_TABLE}', 'hashed_password')
    op.drop_column(f'{settings.DATABASE_RESTAURANT_TABLE}', 'phone')
    op.drop_column(f'{settings.DATABASE_RESTAURANT_TABLE}', 'email')
    op.drop_column(f'{settings.DATABASE_RESTAURANT_TABLE}', 'username')
    # ### end Alembic commands ###
