// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Driver struct {
	ID             uuid.UUID
	Name           string
	PhoneNum       string
	Email          string
	Username       string
	ProfileImg     string
	IsSuperuser    bool
	HashedPassword string
	Age            int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      sql.NullTime
	IsDeleted      bool
}
